In [1]:
# Import Pandas and pathlib
import pandas as pd
from pathlib import Path

In [2]:
#Importing Datasets
song_data = pd.read_csv('Datasets/song_data.csv')
lyric_data = pd.read_csv('Datasets/lyrics-data.csv')
song_data.head(5)

,name,release_date,total_tracks,artists,id,name.1,duration_ms,explicit,id.1,name.2,...,acousticness,instrumentalness,liveness,valence,tempo,type,uri,track_href,analysis_url,time_signature
0,...Ready For It?,2017-09-03,1.0,NaN,06HL4z0CvFAxyc27GXpf02,Taylor Swift,208198.0,False,7zgqtptZvhf8GEmdsM2vp2,...Ready For It?,...,0.0665,0.000000,0.1550,0.453,160.000,audio_features,spotify:track:7zgqtptZvhf8GEmdsM2vp2,https://api.spotify.com/v1/tracks/7zgqtptZvhf8...,https://api.spotify.com/v1/audio-analysis/7zgq...,4.0
1,Life Changes,2017-09-08,14.0,NaN,6x2LnllRG5uGarZMsD4iO8,Thomas Rhett,190227.0,False,4Vxu50qVrQcycjRyJQaZLC,Life Changes,...,0.1000,0.000000,0.0452,0.809,87.972,audio_features,spotify:track:4Vxu50qVrQcycjRyJQaZLC,https://api.spotify.com/v1/tracks/4Vxu50qVrQcy...,https://api.spotify.com/v1/audio-analysis/4Vxu...,4.0
2,24K Magic,2016-11-17,9.0,NaN,0du5cEVh5yTK9QJze8zA0C,Bruno Mars,225983.0,False,6b8Be6ljOzmkOmFslEb23P,24K Magic,...,0.0340,0.000000,0.1530,0.632,106.970,audio_features,spotify:track:6b8Be6ljOzmkOmFslEb23P,https://api.spotify.com/v1/tracks/6b8Be6ljOzmk...,https://api.spotify.com/v1/audio-analysis/6b8B...,4.0
3,รท (Deluxe),2017-03-03,16.0,NaN,6eUKZXaKkcviH0Ku9w2n3V,Ed Sheeran,170827.0,False,0afhq8XCExXpqazXczTSve,Galway Girl,...,0.0735,0.000000,0.3270,0.781,99.943,audio_features,spotify:track:0afhq8XCExXpqazXczTSve,https://api.spotify.com/v1/tracks/0afhq8XCExXp...,https://api.spotify.com/v1/audio-analysis/0afh...,4.0
4,x (Deluxe Edition),2014-06-21,16.0,NaN,6eUKZXaKkcviH0Ku9w2n3V,Ed Sheeran,258987.0,False,1HNkqx9Ahdgi1Ixy2xkKkL,Photograph,...,0.6070,0.000464,0.0986,0.201,107.989,audio_features,spotify:track:1HNkqx9Ahdgi1Ixy2xkKkL,https://api.spotify.com/v1/tracks/1HNkqx9Ahdgi...,https://api.spotify.com/v1/audio-analysis/1HNk...,4.0

In [3]:
lyric_data.head(5)

,ALink,SName,SLink,Lyric,language
0,/ivete-sangalo/,Arerรช,/ivete-sangalo/arere.html,"Tudo o que eu quero nessa vida,\nToda vida, รฉ\...",pt
1,/ivete-sangalo/,Se Eu Nรฃo Te Amasse Tanto Assim,/ivete-sangalo/se-eu-nao-te-amasse-tanto-assim...,Meu coraรงรฃo\nSem direรงรฃo\nVoando sรณ por voar\n...,pt
2,/ivete-sangalo/,Cรฉu da Boca,/ivete-sangalo/chupa-toda.html,ร de babaixรก!\nร de balacubaca!\nร de babaixรก!...,pt
3,/ivete-sangalo/,Quando A Chuva Passar,/ivete-sangalo/quando-a-chuva-passar.html,Quando a chuva passar\n\nPra quรช falar\nSe voc...,pt
4,/ivete-sangalo/,Sorte Grande,/ivete-sangalo/sorte-grande.html,A minha sorte grande foi vocรช cair do cรฉu\nMin...,pt

In [4]:
song_data.info()
print('\nColumns in song_data:',song_data.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10879 entries, 0 to 10878
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              8958 non-null   object
 1   release_date      8958 non-null   object
 2   total_tracks      8958 non-null   float64
 3   artists           0 non-null      float64
 4   id                10879 non-null  object
 5   name.1            10879 non-null  object
 6   duration_ms       8958 non-null   float64
 7   explicit          8958 non-null   object
 8   id.1              8958 non-null   object
 9   name.2            8958 non-null   object
 10  popularity        8958 non-null   float64
 11  danceability      8958 non-null   float64
 12  energy            8958 non-null   float64
 13  key               8958 non-null   float64
 14  loudness          8958 non-null   float64
 15  mode              8958 non-null   float64
 16  speechiness       8958 non-null   float64
 17  acousticness      8958 non-null   float64
 18  instrumentalness  8958 non-null   float64
 19  liveness          8958 non-null   float64
 20  valence           8958 non-null   float64
 21  tempo             8958 non-null   float64
 22  type              8958 non-null   object
 23  uri               8958 non-null   object
 24  track_href        8958 non-null   object
 25  analysis_url      8958 non-null   object
 26  time_signature    8958 non-null   float64
dtypes: float64(16), object(11)
memory usage: 2.2+ MB

Columns in song_data: Index(['name', 'release_date', 'total_tracks', 'artists', 'id', 'name.1',
       'duration_ms', 'explicit', 'id.1', 'name.2', 'popularity',
       'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness',
       'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo',
       'type', 'uri', 'track_href', 'analysis_url', 'time_signature'],
      dtype='object')

In [5]:
lyric_data.info()
print('\nColumns in lyric_data:',lyric_data.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379931 entries, 0 to 379930
Data columns (total 5 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   ALink     379930 non-null  object
 1   SName     379928 non-null  object
 2   SLink     379930 non-null  object
 3   Lyric     379854 non-null  object
 4   language  365296 non-null  object
dtypes: object(5)
memory usage: 14.5+ MB

Columns in lyric_data: Index(['ALink', 'SName', 'SLink', 'Lyric', 'language'], dtype='object')

In [6]:
# Dropping uneccessary columns 
lyric_data = lyric_data.drop(['SLink'], axis = 1)

song_data = song_data.drop(['type', 'uri', 'track_href', 'analysis_url', 'artists', 'id'], axis = 1)

# Dropping rows with popularity = 0 as they are not accurate

song_data = song_data[song_data.popularity != 0]

lyric_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 379931 entries, 0 to 379930
Data columns (total 4 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   ALink     379930 non-null  object
 1   SName     379928 non-null  object
 2   Lyric     379854 non-null  object
 3   language  365296 non-null  object
dtypes: object(4)
memory usage: 11.6+ MB

In [7]:
song_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8095 entries, 1 to 10877
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              6174 non-null   object
 1   release_date      6174 non-null   object
 2   total_tracks      6174 non-null   float64
 3   name.1            8095 non-null   object
 4   duration_ms       6174 non-null   float64
 5   explicit          6174 non-null   object
 6   id.1              6174 non-null   object
 7   name.2            6174 non-null   object
 8   popularity        6174 non-null   float64
 9   danceability      6174 non-null   float64
 10  energy            6174 non-null   float64
 11  key               6174 non-null   float64
 12  loudness          6174 non-null   float64
 13  mode              6174 non-null   float64
 14  speechiness       6174 non-null   float64
 15  acousticness      6174 non-null   float64
 16  instrumentalness  6174 non-null   float64
 17  liveness          6174 non-null   float64
 18  valence           6174 non-null   float64
 19  tempo             6174 non-null   float64
 20  time_signature    6174 non-null   float64
dtypes: float64(15), object(6)
memory usage: 1.4+ MB

In [8]:
#Looking for null values in datasets
print('song_data:')
print(song_data.isnull().sum())
print('\n')
print('lyric_data:')
print(lyric_data.isnull().sum())

song_data:
name                1921
release_date        1921
total_tracks        1921
name.1                 0
duration_ms         1921
explicit            1921
id.1                1921
name.2              1921
popularity          1921
danceability        1921
energy              1921
key                 1921
loudness            1921
mode                1921
speechiness         1921
acousticness        1921
instrumentalness    1921
liveness            1921
valence             1921
tempo               1921
time_signature      1921
dtype: int64


lyric_data:
ALink           1
SName           3
Lyric          77
language    14635
dtype: int64

In [9]:
#Dropping NULL Values
song_data = song_data.dropna()
print(song_data.count())
print('')
lyric_data = lyric_data.dropna()
print(lyric_data.count())

name                6174
release_date        6174
total_tracks        6174
name.1              6174
duration_ms         6174
explicit            6174
id.1                6174
name.2              6174
popularity          6174
danceability        6174
energy              6174
key                 6174
loudness            6174
mode                6174
speechiness         6174
acousticness        6174
instrumentalness    6174
liveness            6174
valence             6174
tempo               6174
time_signature      6174
dtype: int64

ALink       365294
SName       365294
Lyric       365294
language    365294
dtype: int64

In [10]:
#Looking for duplicates in song_data
duplicate_rows_df = song_data[song_data.duplicated()]
print('number of duplicate rows: ', duplicate_rows_df.shape)

number of duplicate rows:  (9, 21)

In [11]:
#Looking for duplicates in lyric_data
duplicate_rows_df = lyric_data[lyric_data.duplicated()]
print('number of duplicate rows: ', duplicate_rows_df.shape)

number of duplicate rows:  (3, 4)

In [12]:
#Dropping the duplicates
song_data = song_data.drop_duplicates()
print('song_data after removing duplicates:')
print(song_data.count())
print('')
lyric_data = lyric_data.drop_duplicates()
print('lyric_data after removing duplicates:')
print(lyric_data.count())

song_data after removing duplicates:
name                6165
release_date        6165
total_tracks        6165
name.1              6165
duration_ms         6165
explicit            6165
id.1                6165
name.2              6165
popularity          6165
danceability        6165
energy              6165
key                 6165
loudness            6165
mode                6165
speechiness         6165
acousticness        6165
instrumentalness    6165
liveness            6165
valence             6165
tempo               6165
time_signature      6165
dtype: int64

lyric_data after removing duplicates:
ALink       365291
SName       365291
Lyric       365291
language    365291
dtype: int64

In [13]:
#Changing artist name in lyric data to match format in song_data
lyric_data['ALink'] = lyric_data['ALink'].str.replace('-',' ')
lyric_data['ALink'] = lyric_data['ALink'].str.replace('/','')
lyric_data

,ALink,SName,Lyric,language
0,ivete sangalo,Arerรช,"Tudo o que eu quero nessa vida,\nToda vida, รฉ\...",pt
1,ivete sangalo,Se Eu Nรฃo Te Amasse Tanto Assim,Meu coraรงรฃo\nSem direรงรฃo\nVoando sรณ por voar\n...,pt
2,ivete sangalo,Cรฉu da Boca,ร de babaixรก!\nร de balacubaca!\nร de babaixรก!...,pt
3,ivete sangalo,Quando A Chuva Passar,Quando a chuva passar\n\nPra quรช falar\nSe voc...,pt
4,ivete sangalo,Sorte Grande,A minha sorte grande foi vocรช cair do cรฉu\nMin...,pt
...,...,...,...,...
379926,clegg johnny,The Waiting,Chorus\nHere we stand waiting on the plain\nDa...,en
379927,clegg johnny,Too Early For The Sky,I nearly disappeared into the mouth of a croco...,en
379928,clegg johnny,Warsaw 1943 (I Never Betrayed The Revolution),"Amambuka, amambuka azothengisa izwe lakithi, i...",en
379929,clegg johnny,When The System Has Fallen,Sweat in the heat for days on end\nwaiting for...,en
379930,clegg johnny,Woman Be My Country,Here we stand on the edge of the day\nFaces me...,en

In [14]:
# Creating a temp df for song_data so that the song_name and artist_name match
temp_song = song_data
temp_song['name.1'] = temp_song['name.1'].str.lower()
temp_song.head(5)

,name,release_date,total_tracks,name.1,duration_ms,explicit,id.1,name.2,popularity,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
1,Life Changes,2017-09-08,14.0,thomas rhett,190227.0,False,4Vxu50qVrQcycjRyJQaZLC,Life Changes,67.0,0.687,...,7.0,-4.370,1.0,0.0576,0.1000,0.000000,0.0452,0.809,87.972,4.0
2,24K Magic,2016-11-17,9.0,bruno mars,225983.0,False,6b8Be6ljOzmkOmFslEb23P,24K Magic,83.0,0.818,...,1.0,-4.282,1.0,0.0797,0.0340,0.000000,0.1530,0.632,106.970,4.0
3,รท (Deluxe),2017-03-03,16.0,ed sheeran,170827.0,False,0afhq8XCExXpqazXczTSve,Galway Girl,82.0,0.624,...,9.0,-3.374,1.0,0.1000,0.0735,0.000000,0.3270,0.781,99.943,4.0
4,x (Deluxe Edition),2014-06-21,16.0,ed sheeran,258987.0,False,1HNkqx9Ahdgi1Ixy2xkKkL,Photograph,88.0,0.614,...,4.0,-10.480,1.0,0.0476,0.6070,0.000464,0.0986,0.201,107.989,4.0
5,Havana (feat. Young Thug),2017-08-03,1.0,camila cabello,216897.0,False,0ofbQMrRDsUaVKq2mGLEAb,Havana (feat. Young Thug),2.0,0.768,...,7.0,-4.323,0.0,0.0312,0.1860,0.000038,0.1040,0.418,104.992,4.0

## Merging the datasets

In [15]:
#Using the Song id as the key for merging the datasets

data = temp_song.merge(lyric_data, left_on = ['name.2','name.1'], right_on = ['SName','ALink'],how='inner').drop(['SName','ALink'], axis = 1)
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1781 entries, 0 to 1780
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              1781 non-null   object
 1   release_date      1781 non-null   object
 2   total_tracks      1781 non-null   float64
 3   name.1            1781 non-null   object
 4   duration_ms       1781 non-null   float64
 5   explicit          1781 non-null   object
 6   id.1              1781 non-null   object
 7   name.2            1781 non-null   object
 8   popularity        1781 non-null   float64
 9   danceability      1781 non-null   float64
 10  energy            1781 non-null   float64
 11  key               1781 non-null   float64
 12  loudness          1781 non-null   float64
 13  mode              1781 non-null   float64
 14  speechiness       1781 non-null   float64
 15  acousticness      1781 non-null   float64
 16  instrumentalness  1781 non-null   float64
 17  liveness          1781 non-null   float64
 18  valence           1781 non-null   float64
 19  tempo             1781 non-null   float64
 20  time_signature    1781 non-null   float64
 21  Lyric             1781 non-null   object
 22  language          1781 non-null   object
dtypes: float64(15), object(8)
memory usage: 333.9+ KB

In [16]:
data.head(5)

,name,release_date,total_tracks,name.1,duration_ms,explicit,id.1,name.2,popularity,danceability,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,Lyric,language
0,รท (Deluxe),2017-03-03,16.0,ed sheeran,170827.0,False,0afhq8XCExXpqazXczTSve,Galway Girl,82.0,0.624,...,1.0,0.1000,0.0735,0.000000,0.3270,0.781,99.943,4.0,She played the fiddle in an Irish band\nBut sh...,en
1,x (Deluxe Edition),2014-06-21,16.0,ed sheeran,258987.0,False,1HNkqx9Ahdgi1Ixy2xkKkL,Photograph,88.0,0.614,...,1.0,0.0476,0.6070,0.000464,0.0986,0.201,107.989,4.0,Loving can hurt\nLoving can hurt sometimes\nBu...,en
2,x (Wembley Edition),2013,24.0,ed sheeran,258987.0,False,6fxVffaTuwjgEk5h9QyRjy,Photograph,69.0,0.614,...,1.0,0.0476,0.6070,0.000464,0.0986,0.201,107.989,4.0,Loving can hurt\nLoving can hurt sometimes\nBu...,en
3,Havana (feat. Young Thug),2017-08-03,1.0,camila cabello,216897.0,False,0ofbQMrRDsUaVKq2mGLEAb,Havana (feat. Young Thug),2.0,0.768,...,0.0,0.0312,0.1860,0.000038,0.1040,0.418,104.992,4.0,"Hey\nHavana, ooh na-na (ay)\nHalf of my heart ...",en
4,Camila,2018-01-12,11.0,camila cabello,217307.0,False,1rfofaqEpACxVEHIZBJe6W,Havana (feat. Young Thug),85.0,0.765,...,1.0,0.0300,0.1840,0.000036,0.1320,0.394,104.988,4.0,"Hey\nHavana, ooh na-na (ay)\nHalf of my heart ...",en

In [17]:
data.info()
print('\nColumns in data:',data.columns)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1781 entries, 0 to 1780
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   name              1781 non-null   object
 1   release_date      1781 non-null   object
 2   total_tracks      1781 non-null   float64
 3   name.1            1781 non-null   object
 4   duration_ms       1781 non-null   float64
 5   explicit          1781 non-null   object
 6   id.1              1781 non-null   object
 7   name.2            1781 non-null   object
 8   popularity        1781 non-null   float64
 9   danceability      1781 non-null   float64
 10  energy            1781 non-null   float64
 11  key               1781 non-null   float64
 12  loudness          1781 non-null   float64
 13  mode              1781 non-null   float64
 14  speechiness       1781 non-null   float64
 15  acousticness      1781 non-null   float64
 16  instrumentalness  1781 non-null   float64
 17  liveness          1781 non-null   float64
 18  valence           1781 non-null   float64
 19  tempo             1781 non-null   float64
 20  time_signature    1781 non-null   float64
 21  Lyric             1781 non-null   object
 22  language          1781 non-null   object
dtypes: float64(15), object(8)
memory usage: 333.9+ KB

Columns in data: Index(['name', 'release_date', 'total_tracks', 'name.1', 'duration_ms',
       'explicit', 'id.1', 'name.2', 'popularity', 'danceability', 'energy',
       'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'Lyric', 'language'],
      dtype='object')

In [18]:
#Renaming Columns for better readabilty

data = data.rename(columns={"name": "album_name", "name.1": "artist_name", "name.2": "song_name", "id.1": "id", "Lyric" : "lyrics"})
data.head(5)

,album_name,release_date,total_tracks,artist_name,duration_ms,explicit,id,song_name,popularity,danceability,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,lyrics,language
0,รท (Deluxe),2017-03-03,16.0,ed sheeran,170827.0,False,0afhq8XCExXpqazXczTSve,Galway Girl,82.0,0.624,...,1.0,0.1000,0.0735,0.000000,0.3270,0.781,99.943,4.0,She played the fiddle in an Irish band\nBut sh...,en
1,x (Deluxe Edition),2014-06-21,16.0,ed sheeran,258987.0,False,1HNkqx9Ahdgi1Ixy2xkKkL,Photograph,88.0,0.614,...,1.0,0.0476,0.6070,0.000464,0.0986,0.201,107.989,4.0,Loving can hurt\nLoving can hurt sometimes\nBu...,en
2,x (Wembley Edition),2013,24.0,ed sheeran,258987.0,False,6fxVffaTuwjgEk5h9QyRjy,Photograph,69.0,0.614,...,1.0,0.0476,0.6070,0.000464,0.0986,0.201,107.989,4.0,Loving can hurt\nLoving can hurt sometimes\nBu...,en
3,Havana (feat. Young Thug),2017-08-03,1.0,camila cabello,216897.0,False,0ofbQMrRDsUaVKq2mGLEAb,Havana (feat. Young Thug),2.0,0.768,...,0.0,0.0312,0.1860,0.000038,0.1040,0.418,104.992,4.0,"Hey\nHavana, ooh na-na (ay)\nHalf of my heart ...",en
4,Camila,2018-01-12,11.0,camila cabello,217307.0,False,1rfofaqEpACxVEHIZBJe6W,Havana (feat. Young Thug),85.0,0.765,...,1.0,0.0300,0.1840,0.000036,0.1320,0.394,104.988,4.0,"Hey\nHavana, ooh na-na (ay)\nHalf of my heart ...",en

In [19]:
# Dropping duplicates with same song name
data = data.drop_duplicates(subset=['song_name'], keep='last')
data.head(5)

,album_name,release_date,total_tracks,artist_name,duration_ms,explicit,id,song_name,popularity,danceability,...,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,lyrics,language
0,รท (Deluxe),2017-03-03,16.0,ed sheeran,170827.0,False,0afhq8XCExXpqazXczTSve,Galway Girl,82.0,0.624,...,1.0,0.1000,0.07350,0.000000,0.327,0.781,99.943,4.0,She played the fiddle in an Irish band\nBut sh...,en
4,Camila,2018-01-12,11.0,camila cabello,217307.0,False,1rfofaqEpACxVEHIZBJe6W,Havana (feat. Young Thug),85.0,0.765,...,1.0,0.0300,0.18400,0.000036,0.132,0.394,104.988,4.0,"Hey\nHavana, ooh na-na (ay)\nHalf of my heart ...",en
5,Unorthodox Jukebox,2012-12-07,10.0,bruno mars,213827.0,False,0nJW01T7XtvILxQgC5J7Wh,When I Was Your Man,88.0,0.612,...,1.0,0.0434,0.93200,0.000000,0.088,0.387,72.795,4.0,"Same bed, but it feels just\nA little bit bigg...",en
7,Picture Show,2012-01-01,11.0,neon trees,177280.0,False,2iUmqdfGZcHIhS3b9E9EWq,Everybody Talks,85.0,0.471,...,1.0,0.0586,0.00301,0.000000,0.313,0.725,154.961,4.0,Hey baby won't you look my way\nI can be your ...,en
9,Red (Deluxe Edition),2012-10-22,22.0,taylor swift,191880.0,False,1OYARuagDrpgNNQ4loO1Cs,We Are Never Ever Getting Back Together,56.0,0.628,...,1.0,0.0916,0.00957,0.000027,0.102,0.750,85.984,4.0,"I remember when we broke up, the first time\nS...",en

## Scaling the numerical values

In [20]:
#making a new dataset with only numerical data
comp_data = data.select_dtypes(include=['float64','int64'])
comp_data.info() 

#making a new dataset with only non numeric data
nn_data = data[['album_name', 'release_date', 'artist_name','explicit', 'song_name','lyrics', 'language']]

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1605 entries, 0 to 1780
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_tracks      1605 non-null   float64
 1   duration_ms       1605 non-null   float64
 2   popularity        1605 non-null   float64
 3   danceability      1605 non-null   float64
 4   energy            1605 non-null   float64
 5   key               1605 non-null   float64
 6   loudness          1605 non-null   float64
 7   mode              1605 non-null   float64
 8   speechiness       1605 non-null   float64
 9   acousticness      1605 non-null   float64
 10  instrumentalness  1605 non-null   float64
 11  liveness          1605 non-null   float64
 12  valence           1605 non-null   float64
 13  tempo             1605 non-null   float64
 14  time_signature    1605 non-null   float64
dtypes: float64(15)
memory usage: 200.6 KB

In [21]:
# Min-Max Normalization
comp_data = (comp_data-comp_data.min())/(comp_data.max()-comp_data.min())
data = pd.concat((nn_data,comp_data), 1)
 
print("Scaled Dataset Using Pandas")
data.head(5)

Scaled Dataset Using Pandas

/var/folders/7_/0098ytkd34q91v84sqxckv_r0000gn/T/ipykernel_23586/4119080528.py:3: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  data = pd.concat((nn_data,comp_data), 1)

,album_name,release_date,artist_name,explicit,song_name,lyrics,language,total_tracks,duration_ms,popularity,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,รท (Deluxe),2017-03-03,ed sheeran,False,Galway Girl,She played the fiddle in an Irish band\nBut sh...,en,0.168539,0.040946,0.870968,...,0.818182,0.907149,1.0,0.171295,0.075075,0.000000,0.332754,0.781564,0.308951,0.75
4,Camila,2018-01-12,camila cabello,False,Havana (feat. Young Thug),"Hey\nHavana, ooh na-na (ay)\nHalf of my heart ...",en,0.112360,0.093116,0.903226,...,0.181818,0.860382,1.0,0.015774,0.187946,0.000036,0.120843,0.377090,0.341004,0.75
5,Unorthodox Jukebox,2012-12-07,bruno mars,False,When I Was Your Man,"Same bed, but it feels just\nA little bit bigg...",en,0.101124,0.089210,0.935484,...,0.000000,0.649956,1.0,0.045545,0.951992,0.000000,0.073028,0.369774,0.136466,0.75
7,Picture Show,2012-01-01,neon trees,False,Everybody Talks,Hey baby won't you look my way\nI can be your ...,en,0.112360,0.048189,0.903226,...,0.727273,0.881206,1.0,0.079316,0.003073,0.000000,0.317540,0.723035,0.658507,0.75
9,Red (Deluxe Edition),2012-10-22,taylor swift,False,We Are Never Ever Getting Back Together,"I remember when we broke up, the first time\nS...",en,0.235955,0.064576,0.591398,...,0.636364,0.783429,1.0,0.152633,0.009774,0.000027,0.088242,0.749164,0.220263,0.75

In [22]:
# Reindexing
data = data.reset_index(drop=True)
data.head(5)

,album_name,release_date,artist_name,explicit,song_name,lyrics,language,total_tracks,duration_ms,popularity,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,รท (Deluxe),2017-03-03,ed sheeran,False,Galway Girl,She played the fiddle in an Irish band\nBut sh...,en,0.168539,0.040946,0.870968,...,0.818182,0.907149,1.0,0.171295,0.075075,0.000000,0.332754,0.781564,0.308951,0.75
1,Camila,2018-01-12,camila cabello,False,Havana (feat. Young Thug),"Hey\nHavana, ooh na-na (ay)\nHalf of my heart ...",en,0.112360,0.093116,0.903226,...,0.181818,0.860382,1.0,0.015774,0.187946,0.000036,0.120843,0.377090,0.341004,0.75
2,Unorthodox Jukebox,2012-12-07,bruno mars,False,When I Was Your Man,"Same bed, but it feels just\nA little bit bigg...",en,0.101124,0.089210,0.935484,...,0.000000,0.649956,1.0,0.045545,0.951992,0.000000,0.073028,0.369774,0.136466,0.75
3,Picture Show,2012-01-01,neon trees,False,Everybody Talks,Hey baby won't you look my way\nI can be your ...,en,0.112360,0.048189,0.903226,...,0.727273,0.881206,1.0,0.079316,0.003073,0.000000,0.317540,0.723035,0.658507,0.75
4,Red (Deluxe Edition),2012-10-22,taylor swift,False,We Are Never Ever Getting Back Together,"I remember when we broke up, the first time\nS...",en,0.235955,0.064576,0.591398,...,0.636364,0.783429,1.0,0.152633,0.009774,0.000027,0.088242,0.749164,0.220263,0.75

In [23]:
# Cleaned dataframe is saved as a csv file
filepath = Path('Datasets/cleaned_data.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
data.to_csv(filepath)